server:
  port: 8082
spring:
  application:
    name: upload-service
  servlet:
    multipart:
      max-file-size: 5MB
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1

# qiniu配置
qiniu:
  AccessKey: mKeiPbEJtEwfoAcWXTfxrYA6WZhddlOtZRMaB01b
  SecretKey: PdAwclRrBL0nQXXJjowA_O5U9LSp7csmPzVvEUxy
  Bucket: fxllongfdfs
  cdn:
      prefix: http://pkbnsx71f.bkt.clouddn.com
#ly:
#  upload:
#    allowTypes:
#      - image/jpeg
#      - image/png
#      - image/bmp
#    baseUrl: http://image.leyou.com/
#fdfs:
#  connect-timeout: 600
#  so-timeout: 2500
#  thumb-image:
#    height: 60
#    width: 60
#  tracker-list:
#    - 192.168.82.100:22122